In [3]:
import statsmodels.api as sm

In [1]:
x=[1,2,3,4,5]
y=[3,5,7,9,11]

In [5]:
X=sm.add_constant(x)

In [6]:
nodel = sm.OLS(y,x)

In [7]:
results = nodel.fit()

In [8]:
results.params

array([2.27272727])

In [9]:
results.pvalues

array([3.81960569e-06])

In [13]:
x=[4,7,6,2,3]   #DIET SCORE
y=[27,29,23,20,21]  #BMI

X=sm.add_constant(x)

nodel = sm.OLS(y,X)
results = nodel.fit()

In [14]:
results.params

array([17.86046512,  1.39534884])

In [15]:
results.pvalues

array([0.01368501, 0.14675265])

In [17]:
pip install plotly

Note: you may need to restart the kernel to use updated packages.


In [19]:
import plotly as pl

In [20]:
import numpy as np

In [22]:
x_giv=np.array([[4,7,6,2,3],[0,1,1,0,0,],[1,1,0,0,1]]).reshape(-1,3)
y_giv=np.array([27,29,23,20,21]) 

X=sm.add_constant(x_giv)

nodel = sm.OLS(y_giv,X)
results = nodel.fit()

In [23]:
results.params

array([21.28384279,  2.33187773,  0.72925764, -1.43668122])

In [24]:
results.pvalues

array([0.03861211, 0.597656  , 0.80747656, 0.3614833 ])